name: app_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0

  firebase_auth: ^5.3.3

  google_sign_in: ^6.2.2

  cloud_firestore: ^5.5.0

  cached_network_image: ^3.4.1
  flutter_notification_channel: ^3.1.0
  lottie: ^3.1.3
  image_picker: ^1.1.2
  emoji_picker_flutter: ^3.1.0
  google_generative_ai: ^0.4.6
  googleapis_auth: ^1.6.0
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # App Assets
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
