// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEZtQ5AHdZyL1EGpohpvD6IMipL54z6o',
    appId: '1:148548664631:android:0ff79096e0e3c289fa2eb2',
    messagingSenderId: '148548664631',
    projectId: 'costechat-1b2c7',
    storageBucket: 'costechat-1b2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrUDoTR1BZ6dR9R0I96dnnrexk1bhUqmQ',
    appId: '1:148548664631:ios:55a9a3a325b94c07fa2eb2',
    messagingSenderId: '148548664631',
    projectId: 'costechat-1b2c7',
    storageBucket: 'costechat-1b2c7.firebasestorage.app',
    androidClientId: '148548664631-ig5bgkiqhb139fdrh9mpgru6qse27tmo.apps.googleusercontent.com',
    iosClientId: '148548664631-0flaio8kln6qolmn1ussf0sd8q6rar9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7CTvwMRPfL0EfRuD6mLLr-S1fH40wqs',
    appId: '1:148548664631:web:aaf3f3c7d5fa8cb0fa2eb2',
    messagingSenderId: '148548664631',
    projectId: 'costechat-1b2c7',
    authDomain: 'costechat-1b2c7.firebaseapp.com',
    storageBucket: 'costechat-1b2c7.firebasestorage.app',
  );

}